version: '3.8'
services:
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: backend_planner_container
    ports:
      - "5000:5000"
    volumes:
      - ./back-end:/backend-activePlanner
    networks:
      - planner-network

  frontend:
    build:
      context: front-end
      dockerfile: Dockerfile
    container_name: frontend_planner_container
    ports:
      - "3000:3000"
    volumes:
      - ./front-end:/frontend-activePlanner
    networks:
      - planner-network

networks:
  planner-network:
    driver: bridge